---
title: "CHIKH_ouissem_test"
author: "Ouissem Chikh"
format: html
---

LINK to the github: https://github.com/Ouissem2005/eval-grades.git


#1.1. Study organisation

##q1. 

```{r}
here::i_am("TEST.Rproj")
library(here)
library(vroom)
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
```

```{r}
courses<-vroom(here("subject-3/courses.csv"))
```
alternatively we can use 'read_delim': 

```{r}
fixing_columns <- read_delim(here("subject-3/courses.csv"),
  delim = ","
)
```

we also check the column types: 

```{r}
spec(courses)
```

##q2.

```{r}
courses|>rename(
    "course name" = course,            
    "identifier" = course_id,
    "semester" = semester,
    "number of grades" = nb_grades
  )|>
  arrange(courses)|>
  knitr::kable()
```


##1.2. students 

##q3. 

```{r}
student<-vroom(here("subject-3/students.csv"))

student|>
  mutate(
    birth_date = as.Date(birth_date),
    sex = as.factor(sex)
  )

spec(student)
```
The birth_date column of the students data frame is of classe Date and the sex is identified as a factor.


##q4. 

we can use vroom: 

```{r}
grades<-vroom(here("subject-3/grades.csv"))
```

OR we can use: 

```{r}
grades <- read_delim(here("subject-3", "grades.csv"),
  delim = "|",
  na = "unknown",
)
```

#2. 

##Q5. 

```{r}
group_counts <- student |>
  count(group)

ggplot(group_counts, aes(x = group, y = n, fill='blue')) +
  geom_col() +
  labs(
    title = "Number of Students per Group",
    x = "Group",
    y = "Number of Students"
  ) +
  theme_minimal()
```

##Q6:

```{r}
student |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill") 
```

##Q7. 

```{r}
library(lubridate)
```
```{r}
student|>
   mutate(
    age = time_length(today() - birth_date, unit = "year"),
    age = round(age)  
  )|>
  ggplot(aes(x = age)) +
  geom_histogram(bins = 15,
    fill = "steelblue")
```

##Q8.

```{r}
student|>
   mutate(
    age = time_length(today() - birth_date, unit = "year"),
    age = round(age)  
  )|>
  group_by(group) |>
  summarize(
    Median_Age = round(median(age, na.rm = TRUE)),
    .groups = 'drop'
  )|>knitr::kable()
```

##Q9. 

```{r}
student|>
   mutate(
    age = time_length(today() - birth_date, unit = "year"),
    age = round(age)  
  )|>
  group_by(group)|>
  slice_max(order_by = age, n = 1, with_ties = FALSE)|>
  select(id, sex, age, group)|>
  arrange(desc(age))|>
  ungroup()|>
  knitr::kable()
```











